# Default worker is for dev only.
# See comaps environments below for production.
name = 'url-processor'
# CoMaps CF Account ID.
account_id = ''
workers_dev = true
compatibility_date = '2025-06-16'
main = './workers-site/index.js'

[site]
bucket = './public'

[build]
command = 'npm i --prefer-offline --no-audit && npm run build'

[vars]
DEBUG = true

[env.comaps]
name = 'url-processor-comaps'
workers_dev = false
# See the full list of handled files in the code.
route = 'comaps.app/*'

[env.comaps.vars]
DEBUG = false
